import Head from "next/head";
import { HeartIcon } from "@heroicons/react/20/solid";

export default function Home() {
  return (
    <>
      <Head>
        <title>GPTask - Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-7xl mx-auto w-full">
        <p className="text-center text-gray-700 text-lg">
          Built with{" "}
          <span className="text-red-500">
            <HeartIcon className="inline w-6 h-6" />
          </span>{" "}
          by <a href="https://github.com/calum-bird">Calum Bird</a> and{" "}
          <a href="https://github.com/chitalian">Justin Torre</a>.
        </p>
      </div>
    </>
  );
}
