import Head from "next/head";
import Layout from "@/components/layout";
import { Prompt } from "@/types";
import { useEffect, useState } from "react";
import { getPrompts } from "@/lib/client/crud";
import PromptList from "@/components/PromptList";
import NewPrompt from "@/components/NewPrompt";

export default function PromptsPage() {
  const [prompts, setPrompts] = useState<Prompt[]>([]);

  useEffect(() => {
    getPrompts().then((prompts) => {
      console.log("Retrieved prompts:", prompts);
      setPrompts(prompts);
    });
  }, []);

  return (
    <>
      <Head>
        <title>GPTask - Prompts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-col justify-center items-start">
          <div className="mt-8 w-full max-w-2xl">
            {prompts.length > 0 ? (
              <PromptList prompts={prompts} />
            ) : (
              <NewPrompt />
            )}
          </div>
        </div>
      </Layout>
    </>
  );
}
